# Generated by Django 5.1.5 on 2025-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeserver',
            old_name='api_key',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='homeserver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='homeserver',
            name='username',
        ),
        migrations.AddField(
            model_name='homeserver',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeserver',
            name='address',
            field=models.TextField(),
        ),
    ]
