# Generated by Django 5.1.5 on 2025-01-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('loginsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LoginSystem',
        ),
    ]
